#theme: jekyll-theme-slate

title            : "Adriaan Ludl"
title_separator  : "-"
subtitle         : "Personal Webpage"
name : "Adriaan Ludl"
#email: "this@that.org"
description: >- # this means to ignore newlines until "baseurl:"
  Adriaan Ludl Personal Webpage
url : https://adluinf.github.io
baseurl : "/"
github_username: adluinf
search: "false"
tagline: "Adriaan Ludl"

# Theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air" 

# Build settings 
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Outputting
permalink: /:categories/:title/
timezone: Europe/Oslo

include:
  - _pages

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Plugins (previously gems:)
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag

author:
  name     : "Adriaan Ludl"
  #avatar   : "/assets/images/bio-photo-2.jpg"
  bio      : "Ubi materia ibi geometria"
  location : "Norway"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/adluinf"
      #    - label: "Google Scholar"
      #icon: "fab fa-fw fa-google"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0003-3461-4644"
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/adluinf"

compress_html:
  clippings: all
  ignore:
    envs: development  # disable compression in dev environment

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

