#theme: jekyll-theme-slate

title            : "Adriaan Ludl"
title_separator  : "-"
subtitle         : "Personal Webpage"
name : "Adriaan Ludl"
#email: "this@that.org"
description: >- # this means to ignore newlines until "baseurl:"
  Adriaan Ludl Personal Webpage
url : https://adluinf.github.io
baseurl : "/"
github_username: adluinf
search: "false"
tagline: "Adriaan Ludl"

# Build settings 
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dirt" 

# config
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-include-cache


author:
  name     : "Adriaan Ludl"
  #avatar   : "/assets/images/bio-photo-2.jpg"
  bio      : "Ubi materia ibi geometria"
  #location : "Eindhoven, The Netherlands"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/adluinf"
      #    - label: "Google Scholar"
      #icon: "fab fa-fw fa-google"



footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/adluinf"
